# Generated by Django 5.0.6 on 2024-05-15 23:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biblesearch", "0002_rename_userprofile_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="clients",
        ),
    ]
