# Generated by Django 5.0.6 on 2024-05-15 23:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biblesearch", "0003_rename_user_clients"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="clients",
            new_name="Users",
        ),
    ]
